# Generated by Django 3.1.5 on 2021-03-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210301_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='following',
            name='user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
