# Generated by Django 3.1.5 on 2021-03-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210301_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('post_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
